// examples/spa/react/src/components/CardDetail.tsx
import { useState } from "react";
import type { Card } from "../types";

interface Props {
  card: Card;
  columns: string[];
  onEdit: (updates: Partial<Pick<Card, "title" | "priority" | "due" | "tags">>) => void;
  onMove: (column: string) => void;
  onDelete: () => void;
  onSetDescription: (content: string) => void;
  onClose: () => void;
}

export default function CardDetail({ card, columns, onEdit, onMove, onDelete, onSetDescription, onClose }: Props) {
  const [editingDesc, setEditingDesc] = useState(false);
  const [descDraft, setDescDraft] = useState(card.description);
  const [editingTitle, setEditingTitle] = useState(false);
  const [titleDraft, setTitleDraft] = useState(card.title);

  const otherColumns = columns.filter((c) => c !== card.column);

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          {editingTitle ? (
            <input
              className="modal-title-input"
              value={titleDraft}
              onChange={(e) => setTitleDraft(e.target.value)}
              onBlur={() => {
                if (titleDraft.trim() && titleDraft !== card.title) {
                  onEdit({ title: titleDraft.trim() });
                }
                setEditingTitle(false);
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter") (e.target as HTMLInputElement).blur();
                if (e.key === "Escape") {
                  setTitleDraft(card.title);
                  setEditingTitle(false);
                }
              }}
              autoFocus
            />
          ) : (
            <h2 className="modal-title" onClick={() => setEditingTitle(true)}>
              {card.title}
            </h2>
          )}
          <button className="modal-close" onClick={onClose}>
            &times;
          </button>
        </div>

        <div className="modal-body">
          <div className="detail-row">
            <span className="detail-label">PRIORITY</span>
            <select
              className="detail-select"
              value={card.priority}
              onChange={(e) => onEdit({ priority: e.target.value as Card["priority"] })}
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
              <option value="critical">Critical</option>
            </select>
          </div>

          <div className="detail-row">
            <span className="detail-label">COLUMN</span>
            <select className="detail-select" value={card.column} onChange={(e) => onMove(e.target.value)}>
              {columns.map((col) => (
                <option key={col} value={col}>
                  {col}
                </option>
              ))}
            </select>
          </div>

          <div className="detail-row">
            <span className="detail-label">DUE DATE</span>
            <input
              className="detail-input"
              type="date"
              value={card.due || ""}
              onChange={(e) => onEdit({ due: e.target.value || (null as unknown as string) })}
            />
          </div>

          <div className="detail-row">
            <span className="detail-label">TAGS</span>
            <input
              className="detail-input"
              type="text"
              value={card.tags.join(", ")}
              placeholder="tag1, tag2, ..."
              onChange={(e) =>
                onEdit({
                  tags: e.target.value
                    .split(",")
                    .map((t) => t.trim())
                    .filter(Boolean),
                })
              }
            />
          </div>

          <div className="detail-description">
            <span className="detail-label">DESCRIPTION</span>
            {editingDesc ? (
              <div className="desc-editor">
                <textarea
                  className="desc-textarea"
                  value={descDraft}
                  onChange={(e) => setDescDraft(e.target.value)}
                  rows={8}
                  autoFocus
                />
                <div className="desc-actions">
                  <button
                    className="btn-primary btn-sm"
                    onClick={() => {
                      onSetDescription(descDraft);
                      setEditingDesc(false);
                    }}
                  >
                    Save
                  </button>
                  <button
                    className="btn-ghost btn-sm"
                    onClick={() => {
                      setDescDraft(card.description);
                      setEditingDesc(false);
                    }}
                  >
                    Cancel
                  </button>
                </div>
              </div>
            ) : (
              <div
                className="desc-preview"
                onClick={() => {
                  setDescDraft(card.description);
                  setEditingDesc(true);
                }}
              >
                {card.description ? (
                  <pre className="desc-content">{card.description}</pre>
                ) : (
                  <p className="desc-placeholder">Click to add a description...</p>
                )}
              </div>
            )}
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn-danger" onClick={onDelete}>
            Delete Card
          </button>
        </div>
      </div>
    </div>
  );
}

// examples/spa/solid/src/components/CardDetail.tsx
import { createSignal, Show, For } from "solid-js";
import type { Card } from "../types";

interface Props {
  card: Card;
  columns: string[];
  onEdit: (updates: Partial<Pick<Card, "title" | "priority" | "due" | "tags">>) => void;
  onMove: (column: string) => void;
  onDelete: () => void;
  onSetDescription: (content: string) => void;
  onClose: () => void;
}

export default function CardDetail(props: Props) {
  const [editingDesc, setEditingDesc] = createSignal(false);
  const [descDraft, setDescDraft] = createSignal(props.card.description);
  const [editingTitle, setEditingTitle] = createSignal(false);
  const [titleDraft, setTitleDraft] = createSignal(props.card.title);

  return (
    <div class="modal-overlay" onClick={props.onClose}>
      <div class="modal" onClick={(e) => e.stopPropagation()}>
        <div class="modal-header">
          <Show
            when={editingTitle()}
            fallback={
              <h2 class="modal-title" onClick={() => setEditingTitle(true)}>
                {props.card.title}
              </h2>
            }
          >
            <input
              class="modal-title-input"
              value={titleDraft()}
              onInput={(e) => setTitleDraft(e.currentTarget.value)}
              onBlur={() => {
                if (titleDraft().trim() && titleDraft() !== props.card.title) {
                  props.onEdit({ title: titleDraft().trim() });
                }
                setEditingTitle(false);
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter") (e.target as HTMLInputElement).blur();
                if (e.key === "Escape") {
                  setTitleDraft(props.card.title);
                  setEditingTitle(false);
                }
              }}
              autofocus
            />
          </Show>
          <button class="modal-close" onClick={props.onClose}>
            &times;
          </button>
        </div>

        <div class="modal-body">
          <div class="detail-row">
            <span class="detail-label">PRIORITY</span>
            <select
              class="detail-select"
              value={props.card.priority}
              onChange={(e) => props.onEdit({ priority: e.currentTarget.value as Card["priority"] })}
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
              <option value="critical">Critical</option>
            </select>
          </div>

          <div class="detail-row">
            <span class="detail-label">COLUMN</span>
            <select
              class="detail-select"
              value={props.card.column}
              onChange={(e) => props.onMove(e.currentTarget.value)}
            >
              <For each={props.columns}>{(col) => <option value={col}>{col}</option>}</For>
            </select>
          </div>

          <div class="detail-row">
            <span class="detail-label">DUE DATE</span>
            <input
              class="detail-input"
              type="date"
              value={props.card.due || ""}
              onChange={(e) => props.onEdit({ due: e.currentTarget.value || (null as unknown as string) })}
            />
          </div>

          <div class="detail-row">
            <span class="detail-label">TAGS</span>
            <input
              class="detail-input"
              type="text"
              value={props.card.tags.join(", ")}
              placeholder="tag1, tag2, ..."
              onChange={(e) =>
                props.onEdit({
                  tags: e.currentTarget.value
                    .split(",")
                    .map((t) => t.trim())
                    .filter(Boolean),
                })
              }
            />
          </div>

          <div class="detail-description">
            <span class="detail-label">DESCRIPTION</span>
            <Show
              when={editingDesc()}
              fallback={
                <div
                  class="desc-preview"
                  onClick={() => {
                    setDescDraft(props.card.description);
                    setEditingDesc(true);
                  }}
                >
                  <Show
                    when={props.card.description}
                    fallback={<p class="desc-placeholder">Click to add a description...</p>}
                  >
                    <pre class="desc-content">{props.card.description}</pre>
                  </Show>
                </div>
              }
            >
              <div class="desc-editor">
                <textarea
                  class="desc-textarea"
                  value={descDraft()}
                  onInput={(e) => setDescDraft(e.currentTarget.value)}
                  rows={8}
                  autofocus
                />
                <div class="desc-actions">
                  <button
                    class="btn-primary btn-sm"
                    onClick={() => {
                      props.onSetDescription(descDraft());
                      setEditingDesc(false);
                    }}
                  >
                    Save
                  </button>
                  <button
                    class="btn-ghost btn-sm"
                    onClick={() => {
                      setDescDraft(props.card.description);
                      setEditingDesc(false);
                    }}
                  >
                    Cancel
                  </button>
                </div>
              </div>
            </Show>
          </div>
        </div>

        <div class="modal-footer">
          <button class="btn-danger" onClick={props.onDelete}>
            Delete Card
          </button>
        </div>
      </div>
    </div>
  );
}
