// examples/spa/react/src/components/SearchBar.tsx
interface Props {
  query: string;
  onQueryChange: (query: string) => void;
}

export default function SearchBar({ query, onQueryChange }: Props) {
  return (
    <div className="search-bar">
      <input
        type="text"
        placeholder="Search cards..."
        value={query}
        onChange={(e) => onQueryChange(e.target.value)}
      />
      {query && (
        <button className="search-clear" onClick={() => onQueryChange("")}>
          &times;
        </button>
      )}
    </div>
  );
}

// examples/spa/solid/src/components/SearchBar.tsx
import { Show } from "solid-js";

interface Props {
  query: string;
  onQueryChange: (query: string) => void;
}

export default function SearchBar(props: Props) {
  return (
    <div class="search-bar">
      <input
        type="text"
        placeholder="Search cards..."
        value={props.query}
        onInput={(e) => props.onQueryChange(e.currentTarget.value)}
      />
      <Show when={props.query}>
        <button class="search-clear" onClick={() => props.onQueryChange("")}>
          &times;
        </button>
      </Show>
    </div>
  );
}
