// examples/spa/svelte/src/components/SearchBar.svelte
<script lang="ts">
  let { query, onQueryChange }: {
    query: string;
    onQueryChange: (query: string) => void;
  } = $props();
</script>

<div class="search-bar">
  <input
    type="text"
    placeholder="Search cards..."
    value={query}
    oninput={(e) => onQueryChange(e.currentTarget.value)}
  />
  {#if query}
    <button class="search-clear" onclick={() => onQueryChange("")}>
      &times;
    </button>
  {/if}
</div>

// examples/spa/solid/src/components/SearchBar.tsx
import { Show } from "solid-js";

interface Props {
  query: string;
  onQueryChange: (query: string) => void;
}

export default function SearchBar(props: Props) {
  return (
    <div class="search-bar">
      <input
        type="text"
        placeholder="Search cards..."
        value={props.query}
        onInput={(e) => props.onQueryChange(e.currentTarget.value)}
      />
      <Show when={props.query}>
        <button class="search-clear" onClick={() => props.onQueryChange("")}>
          &times;
        </button>
      </Show>
    </div>
  );
}
