// examples/vue-tasks/src/App.vue
<script setup lang="ts">
import { ref } from "vue";
import { useSlop } from "@slop-ai/vue";
import { slop } from "./slop";

interface Task {
  id: string;
  title: string;
  done: boolean;
  category: string;
}

const tasks = ref<Task[]>([
  { id: "1", title: "Read SLOP spec", done: false, category: "learning" },
  { id: "2", title: "Build Vue demo", done: true, category: "dev" },
]);

const newTitle = ref("");
const newCategory = ref("general");
let nextId = 3;

function addTask(title: string, category = "general") {
  tasks.value.push({ id: String(nextId++), title, done: false, category });
}

function toggleTask(id: string) {
  const t = tasks.value.find((t) => t.id === id);
  if (t) t.done = !t.done;
}

function deleteTask(id: string) {
  tasks.value = tasks.value.filter((t) => t.id !== id);
}

useSlop(slop, "tasks", () => ({
  type: "collection" as const,
  props: { count: tasks.value.length },
  actions: {
    create: {
      params: { title: "string" as const, category: "string" as const },
      handler: (p: { title: string; category?: string }) =>
        addTask(p.title, p.category),
    },
  },
  items: tasks.value.map((t) => ({
    id: t.id,
    props: { title: t.title, done: t.done, category: t.category },
    actions: {
      toggle: { handler: () => toggleTask(t.id) },
      delete: { handler: () => deleteTask(t.id) },
    },
  })),
}));

function onSubmit() {
  const title = newTitle.value.trim();
  if (!title) return;
  addTask(title, newCategory.value || "general");
  newTitle.value = "";
}
</script>

<template>
  <div :style="{ maxWidth: '520px', margin: '0 auto', padding: '2rem 1rem' }">
    <h1 :style="{ fontSize: '1.5rem', fontWeight: 600, marginBottom: '1.5rem' }">
      Task Manager
    </h1>

    <!-- Add form -->
    <form
      @submit.prevent="onSubmit"
      :style="{
        display: 'flex',
        gap: '0.5rem',
        marginBottom: '1.5rem',
      }"
    >
      <input
        v-model="newTitle"
        placeholder="New task..."
        :style="{
          flex: 1,
          padding: '0.5rem 0.75rem',
          background: '#1c1f26',
          border: '1px solid #30363d',
          borderRadius: '6px',
          color: '#e1e4e8',
          fontSize: '0.875rem',
        }"
      />
      <select
        v-model="newCategory"
        :style="{
          padding: '0.5rem',
          background: '#1c1f26',
          border: '1px solid #30363d',
          borderRadius: '6px',
          color: '#e1e4e8',
          fontSize: '0.875rem',
        }"
      >
        <option value="general">general</option>
        <option value="dev">dev</option>
        <option value="learning">learning</option>
        <option value="chore">chore</option>
      </select>
      <button
        type="submit"
        :style="{
          padding: '0.5rem 1rem',
          background: '#238636',
          border: 'none',
          borderRadius: '6px',
          color: '#fff',
          fontWeight: 600,
          cursor: 'pointer',
          fontSize: '0.875rem',
        }"
      >
        Add
      </button>
    </form>

    <!-- Task list -->
    <div v-if="tasks.length === 0" :style="{ color: '#6e7681', textAlign: 'center', padding: '2rem' }">
      No tasks yet.
    </div>
    <ul :style="{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '0.5rem' }">
      <li
        v-for="task in tasks"
        :key="task.id"
        :style="{
          display: 'flex',
          alignItems: 'center',
          gap: '0.75rem',
          padding: '0.625rem 0.75rem',
          background: '#1c1f26',
          border: '1px solid #30363d',
          borderRadius: '6px',
        }"
      >
        <input
          type="checkbox"
          :checked="task.done"
          @change="toggleTask(task.id)"
          :style="{ cursor: 'pointer' }"
        />
        <span
          :style="{
            flex: 1,
            textDecoration: task.done ? 'line-through' : 'none',
            opacity: task.done ? 0.5 : 1,
          }"
        >
          {{ task.title }}
        </span>
        <span
          :style="{
            fontSize: '0.75rem',
            padding: '0.125rem 0.5rem',
            background: '#30363d',
            borderRadius: '9999px',
            color: '#8b949e',
          }"
        >
          {{ task.category }}
        </span>
        <button
          @click="deleteTask(task.id)"
          :style="{
            background: 'none',
            border: 'none',
            color: '#f85149',
            cursor: 'pointer',
            fontSize: '1rem',
            padding: '0 0.25rem',
          }"
        >
          x
        </button>
      </li>
    </ul>
  </div>
</template>

// examples/nextjs-todos/app/page.tsx
"use client";

import { useState, useEffect, useCallback } from "react";

interface Todo {
  id: string;
  title: string;
  done: boolean;
}

export default function Home() {
  const [todos, setTodos] = useState<Todo[]>([]);
  const [newTitle, setNewTitle] = useState("");

  const load = useCallback(() => {
    fetch("/api/todos")
      .then((r) => r.json())
      .then(setTodos);
  }, []);

  useEffect(() => {
    load();
  }, [load]);

  const add = async () => {
    if (!newTitle.trim()) return;
    await fetch("/api/todos", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ title: newTitle }),
    });
    setNewTitle("");
    load();
  };

  const toggle = async (id: string) => {
    await fetch(`/api/todos?id=${id}`, { method: "PATCH" });
    load();
  };

  const remove = async (id: string) => {
    await fetch(`/api/todos?id=${id}`, { method: "DELETE" });
    load();
  };

  return (
    <div style={{ maxWidth: 600, margin: "0 auto", padding: "40px 20px" }}>
      <h1 style={{ fontSize: 28, marginBottom: 8 }}>Todos</h1>
      <p style={{ color: "#8b949e", marginBottom: 24 }}>
        Next.js + SLOP (WebSocket)
      </p>

      <div style={{ display: "flex", gap: 8, marginBottom: 24 }}>
        <input
          value={newTitle}
          onChange={(e) => setNewTitle(e.target.value)}
          onKeyDown={(e) => e.key === "Enter" && add()}
          placeholder="Add a todo..."
          style={{
            flex: 1,
            padding: "10px 14px",
            background: "#1c2028",
            border: "1px solid #30363d",
            borderRadius: 6,
            color: "#e1e4e8",
            fontSize: 14,
            outline: "none",
          }}
        />
        <button
          onClick={add}
          style={{
            padding: "10px 20px",
            background: "#238636",
            color: "#fff",
            border: "none",
            borderRadius: 6,
            cursor: "pointer",
            fontSize: 14,
          }}
        >
          Add
        </button>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: 4 }}>
        {todos.map((t) => (
          <div
            key={t.id}
            style={{
              display: "flex",
              alignItems: "center",
              gap: 12,
              padding: "12px 16px",
              background: "#161b22",
              borderRadius: 8,
              border: "1px solid #21262d",
            }}
          >
            <input
              type="checkbox"
              checked={t.done}
              onChange={() => toggle(t.id)}
              style={{ width: 18, height: 18, accentColor: "#238636" }}
            />
            <span
              style={{
                flex: 1,
                textDecoration: t.done ? "line-through" : "none",
                color: t.done ? "#484f58" : "#e1e4e8",
              }}
            >
              {t.title}
            </span>
            <button
              onClick={() => remove(t.id)}
              style={{
                background: "none",
                border: "none",
                color: "#da3633",
                cursor: "pointer",
                fontSize: 18,
                padding: 4,
              }}
            >
              x
            </button>
          </div>
        ))}
      </div>

      {todos.length === 0 && (
        <p style={{ color: "#484f58", textAlign: "center", padding: 40 }}>
          No todos yet. Add one above!
        </p>
      )}

      <p
        style={{
          color: "#30363d",
          fontSize: 12,
          marginTop: 40,
          textAlign: "center",
        }}
      >
        {todos.filter((t) => t.done).length}/{todos.length} done - SLOP
        WebSocket at /api/slop
      </p>
    </div>
  );
}
