// examples/spa/react/src/components/Card.tsx
import { useState } from "react";
import type { Card } from "../types";
import { computeSalience } from "../salience";

const PRIORITY_LABELS: Record<string, string> = {
  critical: "CRIT",
  high: "HIGH",
  medium: "MED",
  low: "LOW",
};

interface Props {
  card: Card;
  allColumns: string[];
  onMove: (cardId: string, column: string) => void;
  onDelete: (cardId: string) => void;
  onOpenDetail: (cardId: string) => void;
}

export default function CardItem({ card, allColumns, onMove, onDelete, onOpenDetail }: Props) {
  const [showMenu, setShowMenu] = useState(false);
  const sal = computeSalience(card);
  const otherColumns = allColumns.filter((c) => c !== card.column);
  const isOverdue = card.due && new Date(card.due) < new Date() && card.column !== "done";

  const formatDue = (due: string) => {
    const date = new Date(due);
    return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  };

  return (
    <div
      className={`card ${sal.pinned ? "card-pinned" : ""} ${isOverdue ? "card-overdue" : ""}`}
      onClick={() => onOpenDetail(card.id)}
    >
      <div className="card-header">
        <span className={`card-priority priority-${card.priority}`}>
          {PRIORITY_LABELS[card.priority]}
        </span>
        <button
          className="card-menu-btn"
          onClick={(e) => {
            e.stopPropagation();
            setShowMenu(!showMenu);
          }}
        >
          &#8942;
        </button>
      </div>

      <h3 className="card-title">{card.title}</h3>

      <div className="card-footer">
        {card.due && (
          <span className={`card-due ${isOverdue ? "overdue" : ""}`}>
            {formatDue(card.due)}
          </span>
        )}
        {card.tags.length > 0 && (
          <div className="card-tags">
            {card.tags.map((tag) => (
              <span key={tag} className="card-tag">{tag}</span>
            ))}
          </div>
        )}
        {card.description && <span className="card-has-desc">&#9776;</span>}
      </div>

      {showMenu && (
        <div className="card-menu" onClick={(e) => e.stopPropagation()}>
          {otherColumns.map((col) => (
            <button
              key={col}
              className="card-menu-item"
              onClick={() => {
                onMove(card.id, col);
                setShowMenu(false);
              }}
            >
              Move to {col}
            </button>
          ))}
          <button
            className="card-menu-item danger"
            onClick={() => {
              onDelete(card.id);
              setShowMenu(false);
            }}
          >
            Delete
          </button>
        </div>
      )}
    </div>
  );
}

// examples/spa/vue/src/components/Card.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Card } from "../types";
import { computeSalience } from "../salience";

const PRIORITY_LABELS: Record<string, string> = {
  critical: "CRIT",
  high: "HIGH",
  medium: "MED",
  low: "LOW",
};

const props = defineProps<{
  card: Card;
  allColumns: string[];
}>();

const emit = defineEmits<{
  move: [cardId: string, column: string];
  delete: [cardId: string];
  openDetail: [cardId: string];
}>();

const showMenu = ref(false);

const sal = computeSalience(props.card);
const otherColumns = props.allColumns.filter((c) => c !== props.card.column);
const isOverdue = props.card.due && new Date(props.card.due) < new Date() && props.card.column !== "done";

function formatDue(due: string) {
  const date = new Date(due);
  return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
}
</script>

<template>
  <div
    :class="['card', { 'card-pinned': sal.pinned, 'card-overdue': isOverdue }]"
    @click="emit('openDetail', card.id)"
  >
    <div class="card-header">
      <span :class="['card-priority', `priority-${card.priority}`]">
        {{ PRIORITY_LABELS[card.priority] }}
      </span>
      <button
        class="card-menu-btn"
        @click.stop="showMenu = !showMenu"
      >
        &#8942;
      </button>
    </div>

    <h3 class="card-title">{{ card.title }}</h3>

    <div class="card-footer">
      <span v-if="card.due" :class="['card-due', { overdue: isOverdue }]">
        {{ formatDue(card.due) }}
      </span>
      <div v-if="card.tags.length > 0" class="card-tags">
        <span v-for="tag in card.tags" :key="tag" class="card-tag">{{ tag }}</span>
      </div>
      <span v-if="card.description" class="card-has-desc">&#9776;</span>
    </div>

    <div v-if="showMenu" class="card-menu" @click.stop>
      <button
        v-for="col in otherColumns"
        :key="col"
        class="card-menu-item"
        @click="emit('move', card.id, col); showMenu = false"
      >
        Move to {{ col }}
      </button>
      <button
        class="card-menu-item danger"
        @click="emit('delete', card.id); showMenu = false"
      >
        Delete
      </button>
    </div>
  </div>
</template>
