// examples/spa/angular/src/app/components/card-detail.component.ts
import { Component, input, output, signal } from "@angular/core";
import { FormsModule } from "@angular/forms";
import type { Card } from "../types";

@Component({
  selector: "app-card-detail",
  standalone: true,
  imports: [FormsModule],
  template: `
    <div class="modal-overlay" (click)="close.emit()">
      <div class="modal" (click)="$event.stopPropagation()">
        <div class="modal-header">
          @if (editingTitle()) {
            <input
              class="modal-title-input"
              [ngModel]="titleDraft()"
              (ngModelChange)="titleDraft.set($event)"
              (blur)="submitTitle()"
              (keydown.enter)="$any($event.target).blur()"
              (keydown.escape)="cancelTitleEdit()"
              autofocus
            />
          } @else {
            <h2 class="modal-title" (click)="startTitleEdit()">{{ card().title }}</h2>
          }
          <button class="modal-close" (click)="close.emit()">&times;</button>
        </div>

        <div class="modal-body">
          <div class="detail-row">
            <span class="detail-label">PRIORITY</span>
            <select
              class="detail-select"
              [ngModel]="card().priority"
              (ngModelChange)="edit.emit({ priority: $event })"
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
              <option value="critical">Critical</option>
            </select>
          </div>

          <div class="detail-row">
            <span class="detail-label">COLUMN</span>
            <select
              class="detail-select"
              [ngModel]="card().column"
              (ngModelChange)="move.emit($event)"
            >
              @for (col of columns(); track col) {
                <option [value]="col">{{ col }}</option>
              }
            </select>
          </div>

          <div class="detail-row">
            <span class="detail-label">DUE DATE</span>
            <input
              class="detail-input"
              type="date"
              [ngModel]="card().due || ''"
              (ngModelChange)="edit.emit({ due: $event || null })"
            />
          </div>

          <div class="detail-row">
            <span class="detail-label">TAGS</span>
            <input
              class="detail-input"
              type="text"
              [ngModel]="card().tags.join(', ')"
              (ngModelChange)="handleTagsChange($event)"
              placeholder="tag1, tag2, ..."
            />
          </div>

          <div class="detail-description">
            <span class="detail-label">DESCRIPTION</span>
            @if (editingDesc()) {
              <div class="desc-editor">
                <textarea
                  class="desc-textarea"
                  [ngModel]="descDraft()"
                  (ngModelChange)="descDraft.set($event)"
                  rows="8"
                  autofocus
                ></textarea>
                <div class="desc-actions">
                  <button
                    class="btn-primary btn-sm"
                    (click)="saveDesc()"
                  >
                    Save
                  </button>
                  <button
                    class="btn-ghost btn-sm"
                    (click)="cancelDescEdit()"
                  >
                    Cancel
                  </button>
                </div>
              </div>
            } @else {
              <div
                class="desc-preview"
                (click)="startDescEdit()"
              >
                @if (card().description) {
                  <pre class="desc-content">{{ card().description }}</pre>
                } @else {
                  <p class="desc-placeholder">Click to add a description...</p>
                }
              </div>
            }
          </div>
        </div>

        <div class="modal-footer">
          <button class="btn-danger" (click)="delete.emit()">Delete Card</button>
        </div>
      </div>
    </div>
  `,
})
export class CardDetailComponent {
  card = input.required<Card>();
  columns = input.required<string[]>();
  edit = output<Partial<Pick<Card, "title" | "priority" | "due" | "tags">>>();
  move = output<string>();
  delete = output<void>();
  setDescription = output<string>();
  close = output<void>();

  editingDesc = signal(false);
  descDraft = signal("");
  editingTitle = signal(false);
  titleDraft = signal("");

  startTitleEdit() {
    this.titleDraft.set(this.card().title);
    this.editingTitle.set(true);
  }

  submitTitle() {
    const draft = this.titleDraft().trim();
    if (draft && draft !== this.card().title) {
      this.edit.emit({ title: draft });
    }
    this.editingTitle.set(false);
  }

  cancelTitleEdit() {
    this.titleDraft.set(this.card().title);
    this.editingTitle.set(false);
  }

  startDescEdit() {
    this.descDraft.set(this.card().description);
    this.editingDesc.set(true);
  }

  saveDesc() {
    this.setDescription.emit(this.descDraft());
    this.editingDesc.set(false);
  }

  cancelDescEdit() {
    this.descDraft.set(this.card().description);
    this.editingDesc.set(false);
  }

  handleTagsChange(value: string) {
    this.edit.emit({
      tags: value
        .split(",")
        .map((t) => t.trim())
        .filter(Boolean),
    });
  }
}

// examples/spa/vue/src/components/CardDetail.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Card } from "../types";

const props = defineProps<{
  card: Card;
  columns: string[];
}>();

const emit = defineEmits<{
  edit: [updates: Partial<Pick<Card, "title" | "priority" | "due" | "tags">>];
  move: [column: string];
  delete: [];
  setDescription: [content: string];
  close: [];
}>();

const editingDesc = ref(false);
const descDraft = ref(props.card.description);
const editingTitle = ref(false);
const titleDraft = ref(props.card.title);

function handleTitleBlur() {
  if (titleDraft.value.trim() && titleDraft.value !== props.card.title) {
    emit("edit", { title: titleDraft.value.trim() });
  }
  editingTitle.value = false;
}

function handleTitleKeydown(e: KeyboardEvent) {
  if (e.key === "Enter") (e.target as HTMLInputElement).blur();
  if (e.key === "Escape") {
    titleDraft.value = props.card.title;
    editingTitle.value = false;
  }
}
</script>

<template>
  <div class="modal-overlay" @click="emit('close')">
    <div class="modal" @click.stop>
      <div class="modal-header">
        <input
          v-if="editingTitle"
          class="modal-title-input"
          :value="titleDraft"
          @input="titleDraft = ($event.target as HTMLInputElement).value"
          @blur="handleTitleBlur"
          @keydown="handleTitleKeydown"
          autofocus
        />
        <h2 v-else class="modal-title" @click="editingTitle = true">{{ card.title }}</h2>
        <button class="modal-close" @click="emit('close')">&times;</button>
      </div>

      <div class="modal-body">
        <div class="detail-row">
          <span class="detail-label">PRIORITY</span>
          <select
            class="detail-select"
            :value="card.priority"
            @change="emit('edit', { priority: ($event.target as HTMLSelectElement).value as Card['priority'] })"
          >
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
            <option value="critical">Critical</option>
          </select>
        </div>

        <div class="detail-row">
          <span class="detail-label">COLUMN</span>
          <select
            class="detail-select"
            :value="card.column"
            @change="emit('move', ($event.target as HTMLSelectElement).value)"
          >
            <option v-for="col in columns" :key="col" :value="col">{{ col }}</option>
          </select>
        </div>

        <div class="detail-row">
          <span class="detail-label">DUE DATE</span>
          <input
            class="detail-input"
            type="date"
            :value="card.due || ''"
            @change="emit('edit', { due: ($event.target as HTMLInputElement).value || (null as unknown as string) })"
          />
        </div>

        <div class="detail-row">
          <span class="detail-label">TAGS</span>
          <input
            class="detail-input"
            type="text"
            :value="card.tags.join(', ')"
            placeholder="tag1, tag2, ..."
            @change="emit('edit', { tags: ($event.target as HTMLInputElement).value.split(',').map((t) => t.trim()).filter(Boolean) })"
          />
        </div>

        <div class="detail-description">
          <span class="detail-label">DESCRIPTION</span>
          <div v-if="editingDesc" class="desc-editor">
            <textarea
              class="desc-textarea"
              :value="descDraft"
              @input="descDraft = ($event.target as HTMLTextAreaElement).value"
              rows="8"
              autofocus
            />
            <div class="desc-actions">
              <button
                class="btn-primary btn-sm"
                @click="emit('setDescription', descDraft); editingDesc = false"
              >
                Save
              </button>
              <button
                class="btn-ghost btn-sm"
                @click="descDraft = card.description; editingDesc = false"
              >
                Cancel
              </button>
            </div>
          </div>
          <div
            v-else
            class="desc-preview"
            @click="descDraft = card.description; editingDesc = true"
          >
            <pre v-if="card.description" class="desc-content">{{ card.description }}</pre>
            <p v-else class="desc-placeholder">Click to add a description...</p>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button class="btn-danger" @click="emit('delete')">Delete Card</button>
      </div>
    </div>
  </div>
</template>
