// examples/spa/vue/src/components/BoardSwitcher.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Board } from "../types";

defineProps<{
  boards: Board[];
  activeBoardId: string;
}>();

const emit = defineEmits<{
  navigate: [boardId: string];
  createBoard: [name: string];
}>();

const creating = ref(false);
const newName = ref("");

function handleSubmit() {
  if (newName.value.trim()) {
    emit("createBoard", newName.value.trim());
    newName.value = "";
    creating.value = false;
  }
}
</script>

<template>
  <nav class="board-switcher">
    <button
      v-for="board in boards"
      :key="board.id"
      :class="['board-tab', { active: board.id === activeBoardId }]"
      @click="emit('navigate', board.id)"
    >
      {{ board.name }}
    </button>
    <span v-if="creating" class="board-tab-create">
      <input
        class="board-tab-input"
        type="text"
        placeholder="Board name..."
        v-model="newName"
        @keydown.enter="handleSubmit"
        autofocus
      />
      <button class="btn-ghost" @click="handleSubmit">&#10003;</button>
      <button class="btn-ghost" @click="creating = false">&times;</button>
    </span>
    <button v-else class="board-tab add" @click="creating = true">+</button>
  </nav>
</template>

// examples/spa/svelte/src/components/BoardSwitcher.svelte
<script lang="ts">
  import type { Board } from "../types";

  let { boards, activeBoardId, onNavigate, onCreateBoard }: {
    boards: Board[];
    activeBoardId: string;
    onNavigate: (boardId: string) => void;
    onCreateBoard: (name: string) => void;
  } = $props();

  let creating = $state(false);
  let newName = $state("");

  function handleSubmit() {
    if (newName.trim()) {
      onCreateBoard(newName.trim());
      newName = "";
      creating = false;
    }
  }
</script>

<nav class="board-switcher">
  {#each boards as board (board.id)}
    <button
      class="board-tab {board.id === activeBoardId ? 'active' : ''}"
      onclick={() => onNavigate(board.id)}
    >
      {board.name}
    </button>
  {/each}
  {#if creating}
    <span class="board-tab-create">
      <input
        class="board-tab-input"
        type="text"
        placeholder="Board name..."
        bind:value={newName}
        onkeydown={(e) => e.key === "Enter" && handleSubmit()}
        autofocus
      />
      <button class="btn-ghost" onclick={handleSubmit}>&#10003;</button>
      <button class="btn-ghost" onclick={() => (creating = false)}>&times;</button>
    </span>
  {:else}
    <button class="board-tab add" onclick={() => (creating = true)}>+</button>
  {/if}
</nav>
