// examples/spa/react/src/components/CardDetail.tsx
import { useState } from "react";
import type { Card } from "../types";

interface Props {
  card: Card;
  columns: string[];
  onEdit: (updates: Partial<Pick<Card, "title" | "priority" | "due" | "tags">>) => void;
  onMove: (column: string) => void;
  onDelete: () => void;
  onSetDescription: (content: string) => void;
  onClose: () => void;
}

export default function CardDetail({ card, columns, onEdit, onMove, onDelete, onSetDescription, onClose }: Props) {
  const [editingDesc, setEditingDesc] = useState(false);
  const [descDraft, setDescDraft] = useState(card.description);
  const [editingTitle, setEditingTitle] = useState(false);
  const [titleDraft, setTitleDraft] = useState(card.title);

  const otherColumns = columns.filter((c) => c !== card.column);

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          {editingTitle ? (
            <input
              className="modal-title-input"
              value={titleDraft}
              onChange={(e) => setTitleDraft(e.target.value)}
              onBlur={() => {
                if (titleDraft.trim() && titleDraft !== card.title) {
                  onEdit({ title: titleDraft.trim() });
                }
                setEditingTitle(false);
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter") (e.target as HTMLInputElement).blur();
                if (e.key === "Escape") {
                  setTitleDraft(card.title);
                  setEditingTitle(false);
                }
              }}
              autoFocus
            />
          ) : (
            <h2 className="modal-title" onClick={() => setEditingTitle(true)}>
              {card.title}
            </h2>
          )}
          <button className="modal-close" onClick={onClose}>
            &times;
          </button>
        </div>

        <div className="modal-body">
          <div className="detail-row">
            <span className="detail-label">PRIORITY</span>
            <select
              className="detail-select"
              value={card.priority}
              onChange={(e) => onEdit({ priority: e.target.value as Card["priority"] })}
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
              <option value="critical">Critical</option>
            </select>
          </div>

          <div className="detail-row">
            <span className="detail-label">COLUMN</span>
            <select className="detail-select" value={card.column} onChange={(e) => onMove(e.target.value)}>
              {columns.map((col) => (
                <option key={col} value={col}>
                  {col}
                </option>
              ))}
            </select>
          </div>

          <div className="detail-row">
            <span className="detail-label">DUE DATE</span>
            <input
              className="detail-input"
              type="date"
              value={card.due || ""}
              onChange={(e) => onEdit({ due: e.target.value || (null as unknown as string) })}
            />
          </div>

          <div className="detail-row">
            <span className="detail-label">TAGS</span>
            <input
              className="detail-input"
              type="text"
              value={card.tags.join(", ")}
              placeholder="tag1, tag2, ..."
              onChange={(e) =>
                onEdit({
                  tags: e.target.value
                    .split(",")
                    .map((t) => t.trim())
                    .filter(Boolean),
                })
              }
            />
          </div>

          <div className="detail-description">
            <span className="detail-label">DESCRIPTION</span>
            {editingDesc ? (
              <div className="desc-editor">
                <textarea
                  className="desc-textarea"
                  value={descDraft}
                  onChange={(e) => setDescDraft(e.target.value)}
                  rows={8}
                  autoFocus
                />
                <div className="desc-actions">
                  <button
                    className="btn-primary btn-sm"
                    onClick={() => {
                      onSetDescription(descDraft);
                      setEditingDesc(false);
                    }}
                  >
                    Save
                  </button>
                  <button
                    className="btn-ghost btn-sm"
                    onClick={() => {
                      setDescDraft(card.description);
                      setEditingDesc(false);
                    }}
                  >
                    Cancel
                  </button>
                </div>
              </div>
            ) : (
              <div
                className="desc-preview"
                onClick={() => {
                  setDescDraft(card.description);
                  setEditingDesc(true);
                }}
              >
                {card.description ? (
                  <pre className="desc-content">{card.description}</pre>
                ) : (
                  <p className="desc-placeholder">Click to add a description...</p>
                )}
              </div>
            )}
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn-danger" onClick={onDelete}>
            Delete Card
          </button>
        </div>
      </div>
    </div>
  );
}

// examples/spa/svelte/src/components/CardDetail.svelte
<script lang="ts">
  import type { Card } from "../types";

  let { card, columns, onEdit, onMove, onDelete, onSetDescription, onClose }: {
    card: Card;
    columns: string[];
    onEdit: (updates: Partial<Pick<Card, "title" | "priority" | "due" | "tags">>) => void;
    onMove: (column: string) => void;
    onDelete: () => void;
    onSetDescription: (content: string) => void;
    onClose: () => void;
  } = $props();

  let editingDesc = $state(false);
  let descDraft = $state(card.description);
  let editingTitle = $state(false);
  let titleDraft = $state(card.title);
</script>

<!-- svelte-ignore a11y_click_events_have_key_events -->
<!-- svelte-ignore a11y_no_static_element_interactions -->
<div class="modal-overlay" onclick={onClose}>
  <!-- svelte-ignore a11y_click_events_have_key_events -->
  <!-- svelte-ignore a11y_no_static_element_interactions -->
  <div class="modal" onclick={(e) => e.stopPropagation()}>
    <div class="modal-header">
      {#if editingTitle}
        <input
          class="modal-title-input"
          value={titleDraft}
          oninput={(e) => (titleDraft = e.currentTarget.value)}
          onblur={() => {
            if (titleDraft.trim() && titleDraft !== card.title) {
              onEdit({ title: titleDraft.trim() });
            }
            editingTitle = false;
          }}
          onkeydown={(e) => {
            if (e.key === "Enter") e.currentTarget.blur();
            if (e.key === "Escape") { titleDraft = card.title; editingTitle = false; }
          }}
          autofocus
        />
      {:else}
        <!-- svelte-ignore a11y_click_events_have_key_events -->
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <h2 class="modal-title" onclick={() => (editingTitle = true)}>{card.title}</h2>
      {/if}
      <button class="modal-close" onclick={onClose}>&times;</button>
    </div>

    <div class="modal-body">
      <div class="detail-row">
        <span class="detail-label">PRIORITY</span>
        <select
          class="detail-select"
          value={card.priority}
          onchange={(e) => onEdit({ priority: e.currentTarget.value as Card["priority"] })}
        >
          <option value="low">Low</option>
          <option value="medium">Medium</option>
          <option value="high">High</option>
          <option value="critical">Critical</option>
        </select>
      </div>

      <div class="detail-row">
        <span class="detail-label">COLUMN</span>
        <select
          class="detail-select"
          value={card.column}
          onchange={(e) => onMove(e.currentTarget.value)}
        >
          {#each columns as col (col)}
            <option value={col}>{col}</option>
          {/each}
        </select>
      </div>

      <div class="detail-row">
        <span class="detail-label">DUE DATE</span>
        <input
          class="detail-input"
          type="date"
          value={card.due || ""}
          onchange={(e) => onEdit({ due: e.currentTarget.value || (null as unknown as string) })}
        />
      </div>

      <div class="detail-row">
        <span class="detail-label">TAGS</span>
        <input
          class="detail-input"
          type="text"
          value={card.tags.join(", ")}
          placeholder="tag1, tag2, ..."
          oninput={(e) =>
            onEdit({ tags: e.currentTarget.value.split(",").map((t) => t.trim()).filter(Boolean) })
          }
        />
      </div>

      <div class="detail-description">
        <span class="detail-label">DESCRIPTION</span>
        {#if editingDesc}
          <div class="desc-editor">
            <textarea
              class="desc-textarea"
              value={descDraft}
              oninput={(e) => (descDraft = e.currentTarget.value)}
              rows={8}
              autofocus
            ></textarea>
            <div class="desc-actions">
              <button
                class="btn-primary btn-sm"
                onclick={() => {
                  onSetDescription(descDraft);
                  editingDesc = false;
                }}
              >
                Save
              </button>
              <button
                class="btn-ghost btn-sm"
                onclick={() => {
                  descDraft = card.description;
                  editingDesc = false;
                }}
              >
                Cancel
              </button>
            </div>
          </div>
        {:else}
          <!-- svelte-ignore a11y_click_events_have_key_events -->
          <!-- svelte-ignore a11y_no_static_element_interactions -->
          <div
            class="desc-preview"
            onclick={() => { descDraft = card.description; editingDesc = true; }}
          >
            {#if card.description}
              <pre class="desc-content">{card.description}</pre>
            {:else}
              <p class="desc-placeholder">Click to add a description...</p>
            {/if}
          </div>
        {/if}
      </div>
    </div>

    <div class="modal-footer">
      <button class="btn-danger" onclick={onDelete}>Delete Card</button>
    </div>
  </div>
</div>
