// examples/spa/svelte/src/components/BoardSwitcher.svelte
<script lang="ts">
  import type { Board } from "../types";

  let { boards, activeBoardId, onNavigate, onCreateBoard }: {
    boards: Board[];
    activeBoardId: string;
    onNavigate: (boardId: string) => void;
    onCreateBoard: (name: string) => void;
  } = $props();

  let creating = $state(false);
  let newName = $state("");

  function handleSubmit() {
    if (newName.trim()) {
      onCreateBoard(newName.trim());
      newName = "";
      creating = false;
    }
  }
</script>

<nav class="board-switcher">
  {#each boards as board (board.id)}
    <button
      class="board-tab {board.id === activeBoardId ? 'active' : ''}"
      onclick={() => onNavigate(board.id)}
    >
      {board.name}
    </button>
  {/each}
  {#if creating}
    <span class="board-tab-create">
      <input
        class="board-tab-input"
        type="text"
        placeholder="Board name..."
        bind:value={newName}
        onkeydown={(e) => e.key === "Enter" && handleSubmit()}
        autofocus
      />
      <button class="btn-ghost" onclick={handleSubmit}>&#10003;</button>
      <button class="btn-ghost" onclick={() => (creating = false)}>&times;</button>
    </span>
  {:else}
    <button class="board-tab add" onclick={() => (creating = true)}>+</button>
  {/if}
</nav>

// examples/spa/react/src/components/BoardSwitcher.tsx
import { useState } from "react";
import type { Board } from "../types";

interface Props {
  boards: Board[];
  activeBoardId: string;
  onNavigate: (boardId: string) => void;
  onCreateBoard: (name: string) => void;
}

export default function BoardSwitcher({ boards, activeBoardId, onNavigate, onCreateBoard }: Props) {
  const [creating, setCreating] = useState(false);
  const [newName, setNewName] = useState("");

  const handleSubmit = () => {
    if (newName.trim()) {
      onCreateBoard(newName.trim());
      setNewName("");
      setCreating(false);
    }
  };

  return (
    <nav className="board-switcher">
      {boards.map((board) => (
        <button
          key={board.id}
          className={`board-tab ${board.id === activeBoardId ? "active" : ""}`}
          onClick={() => onNavigate(board.id)}
        >
          {board.name}
        </button>
      ))}
      {creating ? (
        <span className="board-tab-create">
          <input
            className="board-tab-input"
            type="text"
            placeholder="Board name..."
            value={newName}
            onChange={(e) => setNewName(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
            autoFocus
          />
          <button className="btn-ghost" onClick={handleSubmit}>&#10003;</button>
          <button className="btn-ghost" onClick={() => setCreating(false)}>&times;</button>
        </span>
      ) : (
        <button className="board-tab add" onClick={() => setCreating(true)}>+</button>
      )}
    </nav>
  );
}
