// examples/spa/solid/src/components/BoardSwitcher.tsx
import { createSignal, Show, For } from "solid-js";
import type { Board } from "../types";

interface Props {
  boards: Board[];
  activeBoardId: string;
  onNavigate: (boardId: string) => void;
  onCreateBoard: (name: string) => void;
}

export default function BoardSwitcher(props: Props) {
  const [creating, setCreating] = createSignal(false);
  const [newName, setNewName] = createSignal("");

  const handleSubmit = () => {
    if (newName().trim()) {
      props.onCreateBoard(newName().trim());
      setNewName("");
      setCreating(false);
    }
  };

  return (
    <nav class="board-switcher">
      <For each={props.boards}>
        {(board) => (
          <button
            class={`board-tab ${board.id === props.activeBoardId ? "active" : ""}`}
            onClick={() => props.onNavigate(board.id)}
          >
            {board.name}
          </button>
        )}
      </For>
      <Show
        when={creating()}
        fallback={
          <button class="board-tab add" onClick={() => setCreating(true)}>+</button>
        }
      >
        <span class="board-tab-create">
          <input
            class="board-tab-input"
            type="text"
            placeholder="Board name..."
            value={newName()}
            onInput={(e) => setNewName(e.currentTarget.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
            autofocus
          />
          <button class="btn-ghost" onClick={handleSubmit}>&#10003;</button>
          <button class="btn-ghost" onClick={() => setCreating(false)}>&times;</button>
        </span>
      </Show>
    </nav>
  );
}

// examples/spa/react/src/components/BoardSwitcher.tsx
import { useState } from "react";
import type { Board } from "../types";

interface Props {
  boards: Board[];
  activeBoardId: string;
  onNavigate: (boardId: string) => void;
  onCreateBoard: (name: string) => void;
}

export default function BoardSwitcher({ boards, activeBoardId, onNavigate, onCreateBoard }: Props) {
  const [creating, setCreating] = useState(false);
  const [newName, setNewName] = useState("");

  const handleSubmit = () => {
    if (newName.trim()) {
      onCreateBoard(newName.trim());
      setNewName("");
      setCreating(false);
    }
  };

  return (
    <nav className="board-switcher">
      {boards.map((board) => (
        <button
          key={board.id}
          className={`board-tab ${board.id === activeBoardId ? "active" : ""}`}
          onClick={() => onNavigate(board.id)}
        >
          {board.name}
        </button>
      ))}
      {creating ? (
        <span className="board-tab-create">
          <input
            className="board-tab-input"
            type="text"
            placeholder="Board name..."
            value={newName}
            onChange={(e) => setNewName(e.target.value)}
            onKeyDown={(e) => e.key === "Enter" && handleSubmit()}
            autoFocus
          />
          <button className="btn-ghost" onClick={handleSubmit}>&#10003;</button>
          <button className="btn-ghost" onClick={() => setCreating(false)}>&times;</button>
        </span>
      ) : (
        <button className="board-tab add" onClick={() => setCreating(true)}>+</button>
      )}
    </nav>
  );
}
