// examples/spa/solid/src/components/Card.tsx
import { createSignal, Show, For } from "solid-js";
import type { Card } from "../types";
import { computeSalience } from "../salience";

const PRIORITY_LABELS: Record<string, string> = {
  critical: "CRIT",
  high: "HIGH",
  medium: "MED",
  low: "LOW",
};

interface Props {
  card: Card;
  allColumns: string[];
  onMove: (cardId: string, column: string) => void;
  onDelete: (cardId: string) => void;
  onOpenDetail: (cardId: string) => void;
}

export default function CardItem(props: Props) {
  const [showMenu, setShowMenu] = createSignal(false);
  const sal = () => computeSalience(props.card);
  const otherColumns = () => props.allColumns.filter((c) => c !== props.card.column);
  const isOverdue = () => props.card.due && new Date(props.card.due) < new Date() && props.card.column !== "done";

  const formatDue = (due: string) => {
    const date = new Date(due);
    return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  };

  return (
    <div
      class={`card ${sal().pinned ? "card-pinned" : ""} ${isOverdue() ? "card-overdue" : ""}`}
      onClick={() => props.onOpenDetail(props.card.id)}
    >
      <div class="card-header">
        <span class={`card-priority priority-${props.card.priority}`}>{PRIORITY_LABELS[props.card.priority]}</span>
        <button
          class="card-menu-btn"
          onClick={(e) => {
            e.stopPropagation();
            setShowMenu(!showMenu());
          }}
        >
          &#8942;
        </button>
      </div>

      <h3 class="card-title">{props.card.title}</h3>

      <div class="card-footer">
        <Show when={props.card.due}>
          <span class={`card-due ${isOverdue() ? "overdue" : ""}`}>{formatDue(props.card.due!)}</span>
        </Show>
        <Show when={props.card.tags.length > 0}>
          <div class="card-tags">
            <For each={props.card.tags}>{(tag) => <span class="card-tag">{tag}</span>}</For>
          </div>
        </Show>
        <Show when={props.card.description}>
          <span class="card-has-desc">&#9776;</span>
        </Show>
      </div>

      <Show when={showMenu()}>
        <div class="card-menu" onClick={(e) => e.stopPropagation()}>
          <For each={otherColumns()}>
            {(col) => (
              <button
                class="card-menu-item"
                onClick={() => {
                  props.onMove(props.card.id, col);
                  setShowMenu(false);
                }}
              >
                Move to {col}
              </button>
            )}
          </For>
          <button
            class="card-menu-item danger"
            onClick={() => {
              props.onDelete(props.card.id);
              setShowMenu(false);
            }}
          >
            Delete
          </button>
        </div>
      </Show>
    </div>
  );
}

// examples/spa/react/src/components/Card.tsx
import { useState } from "react";
import type { Card } from "../types";
import { computeSalience } from "../salience";

const PRIORITY_LABELS: Record<string, string> = {
  critical: "CRIT",
  high: "HIGH",
  medium: "MED",
  low: "LOW",
};

interface Props {
  card: Card;
  allColumns: string[];
  onMove: (cardId: string, column: string) => void;
  onDelete: (cardId: string) => void;
  onOpenDetail: (cardId: string) => void;
}

export default function CardItem({ card, allColumns, onMove, onDelete, onOpenDetail }: Props) {
  const [showMenu, setShowMenu] = useState(false);
  const sal = computeSalience(card);
  const otherColumns = allColumns.filter((c) => c !== card.column);
  const isOverdue = card.due && new Date(card.due) < new Date() && card.column !== "done";

  const formatDue = (due: string) => {
    const date = new Date(due);
    return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  };

  return (
    <div
      className={`card ${sal.pinned ? "card-pinned" : ""} ${isOverdue ? "card-overdue" : ""}`}
      onClick={() => onOpenDetail(card.id)}
    >
      <div className="card-header">
        <span className={`card-priority priority-${card.priority}`}>
          {PRIORITY_LABELS[card.priority]}
        </span>
        <button
          className="card-menu-btn"
          onClick={(e) => {
            e.stopPropagation();
            setShowMenu(!showMenu);
          }}
        >
          &#8942;
        </button>
      </div>

      <h3 className="card-title">{card.title}</h3>

      <div className="card-footer">
        {card.due && (
          <span className={`card-due ${isOverdue ? "overdue" : ""}`}>
            {formatDue(card.due)}
          </span>
        )}
        {card.tags.length > 0 && (
          <div className="card-tags">
            {card.tags.map((tag) => (
              <span key={tag} className="card-tag">{tag}</span>
            ))}
          </div>
        )}
        {card.description && <span className="card-has-desc">&#9776;</span>}
      </div>

      {showMenu && (
        <div className="card-menu" onClick={(e) => e.stopPropagation()}>
          {otherColumns.map((col) => (
            <button
              key={col}
              className="card-menu-item"
              onClick={() => {
                onMove(card.id, col);
                setShowMenu(false);
              }}
            >
              Move to {col}
            </button>
          ))}
          <button
            className="card-menu-item danger"
            onClick={() => {
              onDelete(card.id);
              setShowMenu(false);
            }}
          >
            Delete
          </button>
        </div>
      )}
    </div>
  );
}
