// examples/spa/svelte/src/components/Card.svelte
<script lang="ts">
  import type { Card } from "../types";
  import { computeSalience } from "../salience";

  const PRIORITY_LABELS: Record<string, string> = {
    critical: "CRIT",
    high: "HIGH",
    medium: "MED",
    low: "LOW",
  };

  let { card, allColumns, onMove, onDelete, onOpenDetail }: {
    card: Card;
    allColumns: string[];
    onMove: (cardId: string, column: string) => void;
    onDelete: (cardId: string) => void;
    onOpenDetail: (cardId: string) => void;
  } = $props();

  let showMenu = $state(false);
  let sal = $derived(computeSalience(card));
  let otherColumns = $derived(allColumns.filter((c) => c !== card.column));
  let isOverdue = $derived(card.due && new Date(card.due) < new Date() && card.column !== "done");

  function formatDue(due: string) {
    const date = new Date(due);
    return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  }
</script>

<div
  class="card {sal.pinned ? 'card-pinned' : ''} {isOverdue ? 'card-overdue' : ''}"
  onclick={() => onOpenDetail(card.id)}
  role="button"
  tabindex="0"
  onkeydown={(e) => e.key === "Enter" && onOpenDetail(card.id)}
>
  <div class="card-header">
    <span class="card-priority priority-{card.priority}">
      {PRIORITY_LABELS[card.priority]}
    </span>
    <button
      class="card-menu-btn"
      onclick={(e) => {
        e.stopPropagation();
        showMenu = !showMenu;
      }}
    >
      &#8942;
    </button>
  </div>

  <h3 class="card-title">{card.title}</h3>

  <div class="card-footer">
    {#if card.due}
      <span class="card-due {isOverdue ? 'overdue' : ''}">
        {formatDue(card.due)}
      </span>
    {/if}
    {#if card.tags.length > 0}
      <div class="card-tags">
        {#each card.tags as tag (tag)}
          <span class="card-tag">{tag}</span>
        {/each}
      </div>
    {/if}
    {#if card.description}
      <span class="card-has-desc">&#9776;</span>
    {/if}
  </div>

  {#if showMenu}
    <!-- svelte-ignore a11y_click_events_have_key_events -->
    <!-- svelte-ignore a11y_no_static_element_interactions -->
    <div class="card-menu" onclick={(e) => e.stopPropagation()}>
      {#each otherColumns as col (col)}
        <button
          class="card-menu-item"
          onclick={() => {
            onMove(card.id, col);
            showMenu = false;
          }}
        >
          Move to {col}
        </button>
      {/each}
      <button
        class="card-menu-item danger"
        onclick={() => {
          onDelete(card.id);
          showMenu = false;
        }}
      >
        Delete
      </button>
    </div>
  {/if}
</div>

// examples/spa/react/src/components/Card.tsx
import { useState } from "react";
import type { Card } from "../types";
import { computeSalience } from "../salience";

const PRIORITY_LABELS: Record<string, string> = {
  critical: "CRIT",
  high: "HIGH",
  medium: "MED",
  low: "LOW",
};

interface Props {
  card: Card;
  allColumns: string[];
  onMove: (cardId: string, column: string) => void;
  onDelete: (cardId: string) => void;
  onOpenDetail: (cardId: string) => void;
}

export default function CardItem({ card, allColumns, onMove, onDelete, onOpenDetail }: Props) {
  const [showMenu, setShowMenu] = useState(false);
  const sal = computeSalience(card);
  const otherColumns = allColumns.filter((c) => c !== card.column);
  const isOverdue = card.due && new Date(card.due) < new Date() && card.column !== "done";

  const formatDue = (due: string) => {
    const date = new Date(due);
    return date.toLocaleDateString("en-US", { month: "short", day: "numeric" });
  };

  return (
    <div
      className={`card ${sal.pinned ? "card-pinned" : ""} ${isOverdue ? "card-overdue" : ""}`}
      onClick={() => onOpenDetail(card.id)}
    >
      <div className="card-header">
        <span className={`card-priority priority-${card.priority}`}>
          {PRIORITY_LABELS[card.priority]}
        </span>
        <button
          className="card-menu-btn"
          onClick={(e) => {
            e.stopPropagation();
            setShowMenu(!showMenu);
          }}
        >
          &#8942;
        </button>
      </div>

      <h3 className="card-title">{card.title}</h3>

      <div className="card-footer">
        {card.due && (
          <span className={`card-due ${isOverdue ? "overdue" : ""}`}>
            {formatDue(card.due)}
          </span>
        )}
        {card.tags.length > 0 && (
          <div className="card-tags">
            {card.tags.map((tag) => (
              <span key={tag} className="card-tag">{tag}</span>
            ))}
          </div>
        )}
        {card.description && <span className="card-has-desc">&#9776;</span>}
      </div>

      {showMenu && (
        <div className="card-menu" onClick={(e) => e.stopPropagation()}>
          {otherColumns.map((col) => (
            <button
              key={col}
              className="card-menu-item"
              onClick={() => {
                onMove(card.id, col);
                setShowMenu(false);
              }}
            >
              Move to {col}
            </button>
          ))}
          <button
            className="card-menu-item danger"
            onClick={() => {
              onDelete(card.id);
              setShowMenu(false);
            }}
          >
            Delete
          </button>
        </div>
      )}
    </div>
  );
}
