// examples/spa/vue/src/components/CardDetail.vue
<script setup lang="ts">
import { ref } from "vue";
import type { Card } from "../types";

const props = defineProps<{
  card: Card;
  columns: string[];
}>();

const emit = defineEmits<{
  edit: [updates: Partial<Pick<Card, "title" | "priority" | "due" | "tags">>];
  move: [column: string];
  delete: [];
  setDescription: [content: string];
  close: [];
}>();

const editingDesc = ref(false);
const descDraft = ref(props.card.description);
const editingTitle = ref(false);
const titleDraft = ref(props.card.title);

function handleTitleBlur() {
  if (titleDraft.value.trim() && titleDraft.value !== props.card.title) {
    emit("edit", { title: titleDraft.value.trim() });
  }
  editingTitle.value = false;
}

function handleTitleKeydown(e: KeyboardEvent) {
  if (e.key === "Enter") (e.target as HTMLInputElement).blur();
  if (e.key === "Escape") {
    titleDraft.value = props.card.title;
    editingTitle.value = false;
  }
}
</script>

<template>
  <div class="modal-overlay" @click="emit('close')">
    <div class="modal" @click.stop>
      <div class="modal-header">
        <input
          v-if="editingTitle"
          class="modal-title-input"
          :value="titleDraft"
          @input="titleDraft = ($event.target as HTMLInputElement).value"
          @blur="handleTitleBlur"
          @keydown="handleTitleKeydown"
          autofocus
        />
        <h2 v-else class="modal-title" @click="editingTitle = true">{{ card.title }}</h2>
        <button class="modal-close" @click="emit('close')">&times;</button>
      </div>

      <div class="modal-body">
        <div class="detail-row">
          <span class="detail-label">PRIORITY</span>
          <select
            class="detail-select"
            :value="card.priority"
            @change="emit('edit', { priority: ($event.target as HTMLSelectElement).value as Card['priority'] })"
          >
            <option value="low">Low</option>
            <option value="medium">Medium</option>
            <option value="high">High</option>
            <option value="critical">Critical</option>
          </select>
        </div>

        <div class="detail-row">
          <span class="detail-label">COLUMN</span>
          <select
            class="detail-select"
            :value="card.column"
            @change="emit('move', ($event.target as HTMLSelectElement).value)"
          >
            <option v-for="col in columns" :key="col" :value="col">{{ col }}</option>
          </select>
        </div>

        <div class="detail-row">
          <span class="detail-label">DUE DATE</span>
          <input
            class="detail-input"
            type="date"
            :value="card.due || ''"
            @change="emit('edit', { due: ($event.target as HTMLInputElement).value || (null as unknown as string) })"
          />
        </div>

        <div class="detail-row">
          <span class="detail-label">TAGS</span>
          <input
            class="detail-input"
            type="text"
            :value="card.tags.join(', ')"
            placeholder="tag1, tag2, ..."
            @change="emit('edit', { tags: ($event.target as HTMLInputElement).value.split(',').map((t) => t.trim()).filter(Boolean) })"
          />
        </div>

        <div class="detail-description">
          <span class="detail-label">DESCRIPTION</span>
          <div v-if="editingDesc" class="desc-editor">
            <textarea
              class="desc-textarea"
              :value="descDraft"
              @input="descDraft = ($event.target as HTMLTextAreaElement).value"
              rows="8"
              autofocus
            />
            <div class="desc-actions">
              <button
                class="btn-primary btn-sm"
                @click="emit('setDescription', descDraft); editingDesc = false"
              >
                Save
              </button>
              <button
                class="btn-ghost btn-sm"
                @click="descDraft = card.description; editingDesc = false"
              >
                Cancel
              </button>
            </div>
          </div>
          <div
            v-else
            class="desc-preview"
            @click="descDraft = card.description; editingDesc = true"
          >
            <pre v-if="card.description" class="desc-content">{{ card.description }}</pre>
            <p v-else class="desc-placeholder">Click to add a description...</p>
          </div>
        </div>
      </div>

      <div class="modal-footer">
        <button class="btn-danger" @click="emit('delete')">Delete Card</button>
      </div>
    </div>
  </div>
</template>

// examples/spa/react/src/components/CardDetail.tsx
import { useState } from "react";
import type { Card } from "../types";

interface Props {
  card: Card;
  columns: string[];
  onEdit: (updates: Partial<Pick<Card, "title" | "priority" | "due" | "tags">>) => void;
  onMove: (column: string) => void;
  onDelete: () => void;
  onSetDescription: (content: string) => void;
  onClose: () => void;
}

export default function CardDetail({ card, columns, onEdit, onMove, onDelete, onSetDescription, onClose }: Props) {
  const [editingDesc, setEditingDesc] = useState(false);
  const [descDraft, setDescDraft] = useState(card.description);
  const [editingTitle, setEditingTitle] = useState(false);
  const [titleDraft, setTitleDraft] = useState(card.title);

  const otherColumns = columns.filter((c) => c !== card.column);

  return (
    <div className="modal-overlay" onClick={onClose}>
      <div className="modal" onClick={(e) => e.stopPropagation()}>
        <div className="modal-header">
          {editingTitle ? (
            <input
              className="modal-title-input"
              value={titleDraft}
              onChange={(e) => setTitleDraft(e.target.value)}
              onBlur={() => {
                if (titleDraft.trim() && titleDraft !== card.title) {
                  onEdit({ title: titleDraft.trim() });
                }
                setEditingTitle(false);
              }}
              onKeyDown={(e) => {
                if (e.key === "Enter") (e.target as HTMLInputElement).blur();
                if (e.key === "Escape") {
                  setTitleDraft(card.title);
                  setEditingTitle(false);
                }
              }}
              autoFocus
            />
          ) : (
            <h2 className="modal-title" onClick={() => setEditingTitle(true)}>
              {card.title}
            </h2>
          )}
          <button className="modal-close" onClick={onClose}>
            &times;
          </button>
        </div>

        <div className="modal-body">
          <div className="detail-row">
            <span className="detail-label">PRIORITY</span>
            <select
              className="detail-select"
              value={card.priority}
              onChange={(e) => onEdit({ priority: e.target.value as Card["priority"] })}
            >
              <option value="low">Low</option>
              <option value="medium">Medium</option>
              <option value="high">High</option>
              <option value="critical">Critical</option>
            </select>
          </div>

          <div className="detail-row">
            <span className="detail-label">COLUMN</span>
            <select className="detail-select" value={card.column} onChange={(e) => onMove(e.target.value)}>
              {columns.map((col) => (
                <option key={col} value={col}>
                  {col}
                </option>
              ))}
            </select>
          </div>

          <div className="detail-row">
            <span className="detail-label">DUE DATE</span>
            <input
              className="detail-input"
              type="date"
              value={card.due || ""}
              onChange={(e) => onEdit({ due: e.target.value || (null as unknown as string) })}
            />
          </div>

          <div className="detail-row">
            <span className="detail-label">TAGS</span>
            <input
              className="detail-input"
              type="text"
              value={card.tags.join(", ")}
              placeholder="tag1, tag2, ..."
              onChange={(e) =>
                onEdit({
                  tags: e.target.value
                    .split(",")
                    .map((t) => t.trim())
                    .filter(Boolean),
                })
              }
            />
          </div>

          <div className="detail-description">
            <span className="detail-label">DESCRIPTION</span>
            {editingDesc ? (
              <div className="desc-editor">
                <textarea
                  className="desc-textarea"
                  value={descDraft}
                  onChange={(e) => setDescDraft(e.target.value)}
                  rows={8}
                  autoFocus
                />
                <div className="desc-actions">
                  <button
                    className="btn-primary btn-sm"
                    onClick={() => {
                      onSetDescription(descDraft);
                      setEditingDesc(false);
                    }}
                  >
                    Save
                  </button>
                  <button
                    className="btn-ghost btn-sm"
                    onClick={() => {
                      setDescDraft(card.description);
                      setEditingDesc(false);
                    }}
                  >
                    Cancel
                  </button>
                </div>
              </div>
            ) : (
              <div
                className="desc-preview"
                onClick={() => {
                  setDescDraft(card.description);
                  setEditingDesc(true);
                }}
              >
                {card.description ? (
                  <pre className="desc-content">{card.description}</pre>
                ) : (
                  <p className="desc-placeholder">Click to add a description...</p>
                )}
              </div>
            )}
          </div>
        </div>

        <div className="modal-footer">
          <button className="btn-danger" onClick={onDelete}>
            Delete Card
          </button>
        </div>
      </div>
    </div>
  );
}
