// examples/spa/vue/src/components/SearchBar.vue
<script setup lang="ts">
defineProps<{
  query: string;
}>();

const emit = defineEmits<{
  "update:query": [query: string];
}>();
</script>

<template>
  <div class="search-bar">
    <input
      type="text"
      placeholder="Search cards..."
      :value="query"
      @input="emit('update:query', ($event.target as HTMLInputElement).value)"
    />
    <button v-if="query" class="search-clear" @click="emit('update:query', '')">
      &times;
    </button>
  </div>
</template>

// examples/spa/react/src/components/SearchBar.tsx
interface Props {
  query: string;
  onQueryChange: (query: string) => void;
}

export default function SearchBar({ query, onQueryChange }: Props) {
  return (
    <div className="search-bar">
      <input
        type="text"
        placeholder="Search cards..."
        value={query}
        onChange={(e) => onQueryChange(e.target.value)}
      />
      {query && (
        <button className="search-clear" onClick={() => onQueryChange("")}>
          &times;
        </button>
      )}
    </div>
  );
}
